compressionLevel: mixed

enableColors: true

enableGlobalCache: false

nodeLinker: node-modules

npmRegistries:
  "https://registry.npmjs.org":
    npmAlwaysAuth: false

npmRegistryServer: "https://registry.npmjs.org/"

supportedArchitectures:
  cpu:
    - x64
    - arm64
  os:
    - darwin
    - linux
    - win32

yarnPath: .yarn/releases/yarn-4.3.1.cjs
