export const info: InfoObject = {
	description:
		"A specification generated by [openapi-devtools](https://github.com/AndrewWalsh/openapi-devtools). Contains 29 endpoints.",
	title: "OpenAPI Specification",
	version: "1.0.0",
};
export const openapi: OpenApiVersion = "3.1.0";
