import { OpenAPIV3_1 } from "openapi-types";
import LicenseObject = OpenAPIV3_1.LicenseObject;

let openAlexLogo = "https://raw.githubusercontent.com/ourresearch/openalex-docs/main/.gitbook/assets/OpenAlex-logo-5.png";
export const info: InfoObject = {
	title: "OpenAlex",
	summary: "OpenAlex API",
	// https://docs.openalex.org/how-to-use-the-api/api-overview
	description: [
		`![](${openAlexLogo})`,
		"**OpenAlex** is a fully open catalog of the global research system.",
		"It's named after the [ancient Library of Alexandria](https://en.wikipedia.org/wiki/Library_of_Alexandria) and made by the nonprofit [OurResearch](https://ourresearch.org/).",
		"This OpenAPI specification is derived from spec generated by [openapi-devtools](https://github.com/AndrewWalsh/openapi-devtools)."
	].join("\n\n"),
	version: "1.0.0",
	license: {
		name: "CC0",
		// identifier: "CC0-1.0",
		url: "https://creativecommons.org/publicdomain/zero/1.0/",
	} satisfies LicenseObject,
};
export const openapi: OpenApiVersion = "3.1.0";
