export const workAttributes = {
	enum: [
		// ...baseSelectionAttributesEnum,
		"abstract_inverted_index",
		"apc_list",
		"apc_paid",
		"authorships",
		"best_oa_location",
		"biblio",
		"cited_by_api_url",
		"cited_by_count",
		"cited_by_percentile_year",
		"concepts",
		"corresponding_author_ids",
		"corresponding_institution_ids",
		"countries_distinct_count",
		"counts_by_year",
		"created_date",
		"doi",
		"fulltext_origin",
		"grants",
		"has_fulltext",
		"ids",
		"institutions_distinct_count",
		"is_authors_truncated",
		"is_paratext",
		"is_retracted",
		"keywords",
		"language",
		"locations_count",
		"locations",
		"mesh",
		"ngrams_url",
		"open_access",
		"primary_location",
		"publication_date",
		"publication_year",
		"referenced_works_count",
		"referenced_works",
		"related_works",
		"relevance_score",
		"sustainable_development_goals",
		"title",
		"type_crossref",
		"type",
		"updated_date",
	],
} satisfies SchemaObject;
